"""Initial migration

Revision ID: d9cb13de0de7
Revises: 
Create Date: 2025-08-23 20:37:20.193893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd9cb13de0de7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
                    sa.Column('org_id', sa.Integer(), nullable=False),
                    sa.Column('org_name', sa.String(), nullable=False),
                    sa.Column('legal_form', sa.VARCHAR(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('org_id')
                    )
    op.create_index(op.f('ix_organizations_org_id'), 'organizations', ['org_id'], unique=False)
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('invoices',
                    sa.Column('invoice_id', sa.Integer(), nullable=False),
                    sa.Column('invoice_sum', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('invoice_type', sa.SMALLINT(), nullable=True),
                    sa.Column('payment_type', sa.VARCHAR(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('invoice_id')
                    )
    op.create_index(op.f('ix_invoices_invoice_id'), 'invoices', ['invoice_id'], unique=False)
    op.create_table('checks',
                    sa.Column('check_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('check_sum', sa.Numeric(precision=10, scale=2), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('org_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('check_id')
                    )
    op.create_index(op.f('ix_checks_check_id'), 'checks', ['check_id'], unique=False)
    op.create_table('items',
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('item_name', sa.VARCHAR(length=255), nullable=False),
                    sa.Column('item_price', sa.Numeric(precision=10, scale=2), nullable=True),
                    sa.Column('item_type', sa.SMALLINT(), nullable=True),
                    sa.Column('item_quantity', sa.Numeric(precision=8, scale=3), nullable=True),
                    sa.Column('item_sum', sa.Numeric(precision=10, scale=2), nullable=True),
                    sa.Column('check_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['check_id'], ['checks.check_id'], ),
                    sa.PrimaryKeyConstraint('item_id')
                    )
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    op.create_table('check_invoices',
                    sa.Column('check_id', sa.Integer(), nullable=False),
                    sa.Column('invoice_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['check_id'], ['checks.check_id'], ),
                    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
                    sa.PrimaryKeyConstraint('check_id', 'invoice_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_invoices')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_checks_check_id'), table_name='checks')
    op.drop_table('checks')
    op.drop_index(op.f('ix_invoices_invoice_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_org_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
